trigger:
  branches:
    include:
      - main  # Change to your branch if needed

pool:
  vmImage: 'ubuntu-latest'

variables:
  mavenVersion: '3.8.4'
  javaVersion: '17'  # Use the Java version your project is using
  springBootAppName: 'shuqa-app.jar'  # Name of your JAR file after build

steps:
  # Step 1: Checkout the code
  - task: GitHubCheckout@1
    inputs:
      repository: 'your-repo-name'
      ref: 'main'

  # Step 2: Set up JDK
  - task: UseJavaVersion@1
    inputs:
      versionSpec: $(javaVersion)
      jdkArchitecture: 'x64'

  # Step 3: Cache Maven Dependencies
  - task: Cache@2
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      path: $(MAVEN_CACHE_FOLDER)
      restoreKeys: |
        maven | "$(Agent.OS)"
        maven

  # Step 4: Maven Clean and Package
  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean package'
      mavenOptions: '-Xmx1024m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(javaVersion)
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  # Step 5: Publish Artifacts
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(System.DefaultWorkingDirectory)/target/$(springBootAppName)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
